import { ResumeHeader } from "@/components/Resume/PDF/ResumeHeader";
import { ResumeFooter } from "@/components/Resume/PDF/ResumeFooter";
import { ResumeItem } from "@/components/Resume/PDF/ResumeItem";
import {
  PDFViewer,
  Document,
  Page,
  View,
} from "@react-pdf/renderer";
import { resumeStyles as styles } from "@/components/Resume/resumeStyles";
import { ResumeSectionHeader } from "@/components/Resume/PDF/ResumeSectionHeader";
import { SummarySection } from "@/components/Resume/PDF/SummarySection";

export const MultiPageResume = (
  props
) => {
  return (
    <>
      <PDFViewer
        style={{
          width: "100%",
          height: "75rem",
        }}
      >
        <Document>
          <Page size="LETTER">
            <View
              style={
                styles.multipage_container
              }
            >
              <ResumeHeader
                name={props.resumeData?.name.toUpperCase()}
                title={
                  props.resumeData
                    ?.title
                }
                email={
                  props.resumeData
                    ?.contactInfo.email
                }
                phone={
                  props.resumeData
                    ?.contactInfo.phone
                }
                website={
                  props.resumeData
                    ?.contactInfo
                    .website
                }
              />
              <SummarySection
                summary1={
                  props.resumeData
                    ?.summary1
                }
                summary2={
                  props.resumeData
                    ?.summary2
                }
              />
              <ResumeSectionHeader
                title={
                  props.resumeData
                    ?.section1.title
                }
                customStyle={
                  styles.margin_bottom_5
                }
              />
              <View>
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1
                      .timeline
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1
                      .timeline.jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1
                      .timeline
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1
                      .timeline
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1
                      .timeline
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1
                      .timeline
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1
                      .timeline
                      .description1
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1
                      .timeline
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1.apple
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1.apple
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1.apple
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1.apple
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1.apple
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1.apple
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1.apple
                      .description1
                  }
                  description2={
                    props.resumeData
                      ?.section1.apple
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1.apple
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1.apple
                      .description4
                  }
                  description5={
                    props.resumeData
                      ?.section1.apple
                      .description5
                  }
                  description6={
                    props.resumeData
                      ?.section1.apple
                      .description6
                  }
                  description7={
                    props.resumeData
                      ?.section1.apple
                      .description7
                  }
                  description8={
                    props.resumeData
                      ?.section1.apple
                      .description8
                  }
                  description9={
                    props.resumeData
                      ?.section1.apple
                      .description9
                  }
                  description10={
                    props.resumeData
                      ?.section1.apple
                      .description10
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1.apple
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1.aquent
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1.aquent
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1.aquent
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1.aquent
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1.aquent
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1.aquent
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1.aquent
                      .description1
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1.aquent
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1.rubrik
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1.rubrik
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1.rubrik
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1.rubrik
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1.rubrik
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1.rubrik
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1.rubrik
                      .description1
                  }
                  description2={
                    props.resumeData
                      ?.section1.rubrik
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1.rubrik
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1.rubrik
                      .description4
                  }
                  description5={
                    props.resumeData
                      ?.section1.rubrik
                      .description5
                  }
                  description6={
                    props.resumeData
                      ?.section1.rubrik
                      .description6
                  }
                  description7={
                    props.resumeData
                      ?.section1.rubrik
                      .description7
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1.rubrik
                      .technologies_used
                  }
                />

                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1.apple2
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1.apple2
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1.apple2
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1.apple2
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1.apple2
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1.apple2
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1.apple2
                      .description1
                  }
                  description2={
                    props.resumeData
                      ?.section1.apple2
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1.apple2
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1.apple2
                      .description4
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1.apple2
                      .technologies_used
                  }
                />

                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1
                      .cloudera.jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description1
                  }
                  description2={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description4
                  }
                  description5={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description5
                  }
                  description6={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description6
                  }
                  description7={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description7
                  }
                  description8={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description8
                  }
                  description9={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description9
                  }
                  description10={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description10
                  }
                  description11={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .description11
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1
                      .cloudera
                      .technologies_used
                  }
                />

                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1.levis
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1.levis
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1.levis
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1.levis
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1.levis
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1.levis
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1.levis
                      .description1
                  }
                  description2={
                    props.resumeData
                      ?.section1.levis
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1.levis
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1.levis
                      .description4
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1.levis
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1.numi
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1.numi
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1.numi
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1.numi
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1.numi
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1.numi
                      .endDateYear
                  }
                  description2={
                    props.resumeData
                      ?.section1.numi
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1.numi
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1.numi
                      .description4
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1.numi
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .endDateYear
                  }
                  description2={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .description2
                  }
                  description3={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .description3
                  }
                  description4={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .description4
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1
                      .stringLetterPublishing
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_5
                  }
                  clientName={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1
                      .theOrion.jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .description1
                  }
                  description2={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .description2
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1
                      .theOrion
                      .technologies_used
                  }
                />
                <ResumeItem
                  customStyle={
                    styles.margin_bottom_10
                  }
                  clientName={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .clientName
                  }
                  jobTitle={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .jobTitle
                  }
                  startDateMonth={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .startDateMonth
                  }
                  endDateMonth={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .endDateMonth
                  }
                  startDateYear={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .endDateYear
                  }
                  description1={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .description1
                  }
                  technologies_used={
                    props.resumeData
                      ?.section1
                      .truckerDeluxe
                      .technologies_used
                  }
                />
                <ResumeFooter
                  educationTitle={
                    props.resumeData
                      ?.section2
                      .education.title
                  }
                  degree={
                    props.resumeData
                      ?.section2
                      .education.degree
                  }
                  school={
                    props.resumeData
                      ?.section2
                      .education.school
                  }
                  startDateYear={
                    props.resumeData
                      ?.section2
                      .education
                      .startDateYear
                  }
                  endDateYear={
                    props.resumeData
                      ?.section2
                      .education
                      .endDateYear
                  }
                  description={
                    props.resumeData
                      ?.section2
                      .education
                      .longDescription
                  }
                  skillsTitle={
                    props.resumeData
                      ?.section2.skills
                      .title
                  }
                  skill1Title={
                    props.resumeData
                      ?.section2.skills
                      .skill1.title
                  }
                  skill2Title={
                    props.resumeData
                      ?.section2.skills
                      .skill2.title
                  }
                  skill3Title={
                    props.resumeData
                      ?.section2.skills
                      .skill3.title
                  }
                  skill4Title={
                    props.resumeData
                      ?.section2.skills
                      .skill4.title
                  }
                  skill5Title={
                    props.resumeData
                      ?.section2.skills
                      .skill5.title
                  }
                  skill6Title={
                    props.resumeData
                      ?.section2.skills
                      .skill6.title
                  }
                  skill1Description={
                    props.resumeData
                      ?.section2.skills
                      .skill1
                      .description
                  }
                  skill2Description={
                    props.resumeData
                      ?.section2.skills
                      .skill2
                      .description
                  }
                  skill3Description={
                    props.resumeData
                      ?.section2.skills
                      .skill3
                      .description
                  }
                  skill4Description={
                    props.resumeData
                      ?.section2.skills
                      .skill4
                      .description
                  }
                  skill5Description={
                    props.resumeData
                      ?.section2.skills
                      .skill5
                      .description
                  }
                  skill6Description={
                    props.resumeData
                      ?.section2.skills
                      .skill6
                      .description
                  }
                />
              </View>
            </View>
          </Page>
        </Document>
      </PDFViewer>
    </>
  );
};
