runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  # Serve static files
  #- url: /(.*\.(gif|png|jpg|css|js|ico))$
  #  static_files: dist/\1
  #  upload: dist/.*\.(gif|png|jpg|css|js|ico)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
