runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|json)$
    mime_type: application/javascript
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
