runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /(.*\.css)$
    static_files: dist/\1
    upload: dist/.*\.css$
    mime_type: text/css

  - url: /(.*\.js)$
    static_files: dist/\1
    upload: dist/.*\.js$
    mime_type: application/javascript

  - url: /(.*\.(png|jpg|jpeg|gif|ico|json))$
    static_files: dist/\1
    upload: dist/.*\.(png|jpg|jpeg|gif|ico|json)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
