runtime: nodejs22
env: standard
instance_class: F1

automatic_scaling:
    max_instances: 1

handlers:
    - url: /assets
      static_dir: dist/assets
      expiration: "365d"
      http_headers:
          Cache-Control: "public, max-age=31536000, immutable"

    - url: /robots.txt
      static_files: dist/robots.txt
      upload: dist/robots.txt

    - url: /sitemap.xml
      static_files: dist/sitemap.xml
      upload: dist/sitemap.xml

    - url: /
      static_files: dist/index.html
      upload: dist/index.html

    - url: /.*
      script: auto

env_variables:
    NODE_ENV: "production"
