runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /static
    static_dir: dist

  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: "production"
